[project]
name = "doppio"
version = "0.0.1"
description = "A dream."
requires-python = ">=3.10"

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
